version: "3"

volumes:
    gitweb:

services:
    gitweb:
        image: fraoustin/gitweb
        build:
            context: .
            dockerfile: Dockerfile.CN
        ports:
            - 80:80
        volumes:
            - gitweb:/var/lib/git