version: "3"

volumes:
    gitweb-1:
    gitweb-2:
    gitweb-3:


services:

    gitweb-test1:
        build: .
        image: ${IMAGE_NAME}:test
        container_name: gitweb-test1
        hostname: gitweb-test1
        environment:
            - CONTAINER_TIMEZONE=Europe/Paris
            - GITUSER=gituser
            - GITPASSWORD=gitpassword
            - GITPROJECT=test
            - my_uri=/
            - GITHIGHLIGHT=1
            - IHM=mdl
        restart: always
        volumes:
            - gitweb-1:/var/lib/git/
        ports:
            - 8080:80

    gitweb-test2:
        image: ${IMAGE_NAME}:test
        container_name: gitweb-test2
        hostname: gitweb-test2
        environment:
            - CONTAINER_TIMEZONE=Europe/Paris
            - GITUSER=gituser
            - GITPASSWORD=gitpassword
            - GITPROJECT=test
            - FORCEPUSH="true"
            - my_uri=/path/to/
        restart: always
        volumes:
            - gitweb-2:/var/lib/git/
            - ./test/:/opt/gitweb/remote/
        links:
            - gitweb-test1
        ports:
            - 8081:80
    gitweb-test3:
        image: ${IMAGE_NAME}:test
        container_name: gitweb-test3
        hostname: gitweb-test3
        environment:
            - CONTAINER_TIMEZONE=Europe/Paris
            - GITUSER=gituser
            - GITPASSWORD=gitpassword
            - GITPROJECT=test3
            - FORCEPUSH=""
            - my_uri=/
        restart: always
        volumes:
            - gitweb-3:/var/lib/git/
            - ./test/:/opt/gitweb/test/
        links:
            - gitweb-test1
            - gitweb-test2
        ports:
            - 8082:80
