version: "3.8"

volumes:
    gitweb:


services:
    gitweb:
        image: ${REGISTRY}${REGISTRY+/}fraoustin/gitweb${TAG+:}${TAG}
        container_name: gitweb
        hostname: gitweb-test
        build:
            # context: https://github.com/fraoustin/gitweb.git
            context: .
            dockerfile: Dockerfile.CN
            platforms:
                - "linux/amd64"
                - "linux/386"
                - "linux/arm64/v8"
                - "linux/arm/v7"

# e.g
# linux:        export REGISTRY=docker.io
# powershell:   $env:REGISTRY='registry.your.domain'
# docker compose -f .\docker-compose.build.yaml build
# docker compose -f .\docker-compose.build.yaml push